[request_definition]
r = sub, lob, page, mod, sec, access

[policy_definition]
p = perm, lob, page, mod, sec, access
p2 = key, lob, parent, meta

[role_definition]
g = _, _
g2 = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.perm) && r.lob == p.lob && r.page == p.page && r.mod == p.mod && r.sec == p.sec && r.access == p.access
