[request_definition]
r = sub, lob, page, mod, sec, access
r2 = sub, key
r3 = sub, lob, page, mod, sec, field, access

[policy_definition]
p = perm, lob, page, mod, sec, access
p2 = key, lob, parent, meta
p3 = perm, lob, page, mod, sec, field, access

[role_definition]
g = _, _
g2 = _, _, _
g3 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g3_has_policy(r.sub, p.perm) && r.lob == p.lob && r.page == p.page && r.mod == p.mod && r.sec == p.sec && r.access == p.access
m2 = g3_has_policy(r2.sub, p2.key)
m3 = g3_has_policy(r3.sub, p3.perm) && r3.lob == p3.lob && r3.page == p3.page && r3.mod == p3.mod && r3.sec == p3.sec && r3.field == p3.field && r3.access == p3.access

